//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRZCV.dados_perso {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="dados_perso.ZWS_PEP_ENVIO_DADOS_PERSONALIZ")]
    public interface ZWS_PEP_ENVIO_DADOS_PERSONALIZ {
        
        // CODEGEN: Generating message contract since the operation ZF_PEP_ENVIO_DADOS_PERSONALIZ is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZResponse1 ZF_PEP_ENVIO_DADOS_PERSONALIZ(MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_ENVIO_DADOS_PERSONALIZ : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string mRZ1_INField;
        
        private string mRZ2_INField;
        
        private string tIPO_INField;
        
        private string uSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string MRZ1_IN {
            get {
                return this.mRZ1_INField;
            }
            set {
                this.mRZ1_INField = value;
                this.RaisePropertyChanged("MRZ1_IN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string MRZ2_IN {
            get {
                return this.mRZ2_INField;
            }
            set {
                this.mRZ2_INField = value;
                this.RaisePropertyChanged("MRZ2_IN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TIPO_IN {
            get {
                return this.tIPO_INField;
            }
            set {
                this.tIPO_INField = value;
                this.RaisePropertyChanged("TIPO_IN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
                this.RaisePropertyChanged("USER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_ENVIO_DADOS_PERSONALIZResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string aLTURAField;
        
        private string aNONASCIMENTOField;
        
        private string aPELIDOField;
        
        private string aSSINATURAField;
        
        private string dATAEMISSAOField;
        
        private string dATAVALIDADEField;
        
        private string dESCRICAOField;
        
        private string dIANASCIMENTOField;
        
        private string eMISSORAUTORIDADEField;
        
        private string eSTADOField;
        
        private string fOTOGRAFIAField;
        
        private string fOTOGRAFIACHIPField;
        
        private string lOCALNASCIMENTOField;
        
        private string mESNASCIMENTOField;
        
        private string mRZ1_OUTField;
        
        private string mRZ2_OUTField;
        
        private string nACIONALIDADEField;
        
        private string nACIONALIDADEABVField;
        
        private string nOMEPROPRIOField;
        
        private string nUMEROIDENTIFICACAOField;
        
        private string[] oBSERVACOESField;
        
        private string sEXOField;
        
        private string tIPODOCUMENTOField;
        
        private string tIPO_OUTField;
        
        private byte t_LINHAField;
        
        private string vERSAODOCUMENTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string ALTURA {
            get {
                return this.aLTURAField;
            }
            set {
                this.aLTURAField = value;
                this.RaisePropertyChanged("ALTURA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ANONASCIMENTO {
            get {
                return this.aNONASCIMENTOField;
            }
            set {
                this.aNONASCIMENTOField = value;
                this.RaisePropertyChanged("ANONASCIMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string APELIDO {
            get {
                return this.aPELIDOField;
            }
            set {
                this.aPELIDOField = value;
                this.RaisePropertyChanged("APELIDO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string ASSINATURA {
            get {
                return this.aSSINATURAField;
            }
            set {
                this.aSSINATURAField = value;
                this.RaisePropertyChanged("ASSINATURA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string DATAEMISSAO {
            get {
                return this.dATAEMISSAOField;
            }
            set {
                this.dATAEMISSAOField = value;
                this.RaisePropertyChanged("DATAEMISSAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string DATAVALIDADE {
            get {
                return this.dATAVALIDADEField;
            }
            set {
                this.dATAVALIDADEField = value;
                this.RaisePropertyChanged("DATAVALIDADE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string DESCRICAO {
            get {
                return this.dESCRICAOField;
            }
            set {
                this.dESCRICAOField = value;
                this.RaisePropertyChanged("DESCRICAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string DIANASCIMENTO {
            get {
                return this.dIANASCIMENTOField;
            }
            set {
                this.dIANASCIMENTOField = value;
                this.RaisePropertyChanged("DIANASCIMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string EMISSORAUTORIDADE {
            get {
                return this.eMISSORAUTORIDADEField;
            }
            set {
                this.eMISSORAUTORIDADEField = value;
                this.RaisePropertyChanged("EMISSORAUTORIDADE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string ESTADO {
            get {
                return this.eSTADOField;
            }
            set {
                this.eSTADOField = value;
                this.RaisePropertyChanged("ESTADO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string FOTOGRAFIA {
            get {
                return this.fOTOGRAFIAField;
            }
            set {
                this.fOTOGRAFIAField = value;
                this.RaisePropertyChanged("FOTOGRAFIA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string FOTOGRAFIACHIP {
            get {
                return this.fOTOGRAFIACHIPField;
            }
            set {
                this.fOTOGRAFIACHIPField = value;
                this.RaisePropertyChanged("FOTOGRAFIACHIP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string LOCALNASCIMENTO {
            get {
                return this.lOCALNASCIMENTOField;
            }
            set {
                this.lOCALNASCIMENTOField = value;
                this.RaisePropertyChanged("LOCALNASCIMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string MESNASCIMENTO {
            get {
                return this.mESNASCIMENTOField;
            }
            set {
                this.mESNASCIMENTOField = value;
                this.RaisePropertyChanged("MESNASCIMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string MRZ1_OUT {
            get {
                return this.mRZ1_OUTField;
            }
            set {
                this.mRZ1_OUTField = value;
                this.RaisePropertyChanged("MRZ1_OUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string MRZ2_OUT {
            get {
                return this.mRZ2_OUTField;
            }
            set {
                this.mRZ2_OUTField = value;
                this.RaisePropertyChanged("MRZ2_OUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string NACIONALIDADE {
            get {
                return this.nACIONALIDADEField;
            }
            set {
                this.nACIONALIDADEField = value;
                this.RaisePropertyChanged("NACIONALIDADE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string NACIONALIDADEABV {
            get {
                return this.nACIONALIDADEABVField;
            }
            set {
                this.nACIONALIDADEABVField = value;
                this.RaisePropertyChanged("NACIONALIDADEABV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string NOMEPROPRIO {
            get {
                return this.nOMEPROPRIOField;
            }
            set {
                this.nOMEPROPRIOField = value;
                this.RaisePropertyChanged("NOMEPROPRIO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string NUMEROIDENTIFICACAO {
            get {
                return this.nUMEROIDENTIFICACAOField;
            }
            set {
                this.nUMEROIDENTIFICACAOField = value;
                this.RaisePropertyChanged("NUMEROIDENTIFICACAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] OBSERVACOES {
            get {
                return this.oBSERVACOESField;
            }
            set {
                this.oBSERVACOESField = value;
                this.RaisePropertyChanged("OBSERVACOES");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string SEXO {
            get {
                return this.sEXOField;
            }
            set {
                this.sEXOField = value;
                this.RaisePropertyChanged("SEXO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string TIPODOCUMENTO {
            get {
                return this.tIPODOCUMENTOField;
            }
            set {
                this.tIPODOCUMENTOField = value;
                this.RaisePropertyChanged("TIPODOCUMENTO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string TIPO_OUT {
            get {
                return this.tIPO_OUTField;
            }
            set {
                this.tIPO_OUTField = value;
                this.RaisePropertyChanged("TIPO_OUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public byte T_LINHA {
            get {
                return this.t_LINHAField;
            }
            set {
                this.t_LINHAField = value;
                this.RaisePropertyChanged("T_LINHA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string VERSAODOCUMENTO {
            get {
                return this.vERSAODOCUMENTOField;
            }
            set {
                this.vERSAODOCUMENTOField = value;
                this.RaisePropertyChanged("VERSAODOCUMENTO");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_ENVIO_DADOS_PERSONALIZRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZ ZF_PEP_ENVIO_DADOS_PERSONALIZ;
        
        public ZF_PEP_ENVIO_DADOS_PERSONALIZRequest() {
        }
        
        public ZF_PEP_ENVIO_DADOS_PERSONALIZRequest(MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZ ZF_PEP_ENVIO_DADOS_PERSONALIZ) {
            this.ZF_PEP_ENVIO_DADOS_PERSONALIZ = ZF_PEP_ENVIO_DADOS_PERSONALIZ;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_ENVIO_DADOS_PERSONALIZResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZResponse ZF_PEP_ENVIO_DADOS_PERSONALIZResponse;
        
        public ZF_PEP_ENVIO_DADOS_PERSONALIZResponse1() {
        }
        
        public ZF_PEP_ENVIO_DADOS_PERSONALIZResponse1(MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZResponse ZF_PEP_ENVIO_DADOS_PERSONALIZResponse) {
            this.ZF_PEP_ENVIO_DADOS_PERSONALIZResponse = ZF_PEP_ENVIO_DADOS_PERSONALIZResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_PEP_ENVIO_DADOS_PERSONALIZChannel : MRZCV.dados_perso.ZWS_PEP_ENVIO_DADOS_PERSONALIZ, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_PEP_ENVIO_DADOS_PERSONALIZClient : System.ServiceModel.ClientBase<MRZCV.dados_perso.ZWS_PEP_ENVIO_DADOS_PERSONALIZ>, MRZCV.dados_perso.ZWS_PEP_ENVIO_DADOS_PERSONALIZ {
        
        public ZWS_PEP_ENVIO_DADOS_PERSONALIZClient() {
        }
        
        public ZWS_PEP_ENVIO_DADOS_PERSONALIZClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_PEP_ENVIO_DADOS_PERSONALIZClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_ENVIO_DADOS_PERSONALIZClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_ENVIO_DADOS_PERSONALIZClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZResponse1 MRZCV.dados_perso.ZWS_PEP_ENVIO_DADOS_PERSONALIZ.ZF_PEP_ENVIO_DADOS_PERSONALIZ(MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZRequest request) {
            return base.Channel.ZF_PEP_ENVIO_DADOS_PERSONALIZ(request);
        }
        
        public MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZResponse ZF_PEP_ENVIO_DADOS_PERSONALIZ(MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZ ZF_PEP_ENVIO_DADOS_PERSONALIZ1) {
            MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZRequest inValue = new MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZRequest();
            inValue.ZF_PEP_ENVIO_DADOS_PERSONALIZ = ZF_PEP_ENVIO_DADOS_PERSONALIZ1;
            MRZCV.dados_perso.ZF_PEP_ENVIO_DADOS_PERSONALIZResponse1 retVal = ((MRZCV.dados_perso.ZWS_PEP_ENVIO_DADOS_PERSONALIZ)(this)).ZF_PEP_ENVIO_DADOS_PERSONALIZ(inValue);
            return retVal.ZF_PEP_ENVIO_DADOS_PERSONALIZResponse;
        }
    }
}
