//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRZCV.Retirar_pep {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="Retirar_pep.ZWS_PEP_RETIRAR_PEP")]
    public interface ZWS_PEP_RETIRAR_PEP {
        
        // CODEGEN: Generating message contract since the operation ZF_PEP_RETIRAR_PEP is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEPResponse1 ZF_PEP_RETIRAR_PEP(MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEPRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_RETIRAR_PEP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] lISTA_INField;
        
        private string tIPOField;
        
        private string uSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] LISTA_IN {
            get {
                return this.lISTA_INField;
            }
            set {
                this.lISTA_INField = value;
                this.RaisePropertyChanged("LISTA_IN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
                this.RaisePropertyChanged("TIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
                this.RaisePropertyChanged("USER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_RETIRAR_PEPResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESCRICAOField;
        
        private string dESTINOField;
        
        private string[] lISTA_OUTField;
        
        private string lOTEField;
        
        private string sTATUSField;
        
        private string tOTALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DESCRICAO {
            get {
                return this.dESCRICAOField;
            }
            set {
                this.dESCRICAOField = value;
                this.RaisePropertyChanged("DESCRICAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DESTINO {
            get {
                return this.dESTINOField;
            }
            set {
                this.dESTINOField = value;
                this.RaisePropertyChanged("DESTINO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] LISTA_OUT {
            get {
                return this.lISTA_OUTField;
            }
            set {
                this.lISTA_OUTField = value;
                this.RaisePropertyChanged("LISTA_OUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOTE {
            get {
                return this.lOTEField;
            }
            set {
                this.lOTEField = value;
                this.RaisePropertyChanged("LOTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
                this.RaisePropertyChanged("TOTAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_RETIRAR_PEPRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEP ZF_PEP_RETIRAR_PEP;
        
        public ZF_PEP_RETIRAR_PEPRequest() {
        }
        
        public ZF_PEP_RETIRAR_PEPRequest(MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEP ZF_PEP_RETIRAR_PEP) {
            this.ZF_PEP_RETIRAR_PEP = ZF_PEP_RETIRAR_PEP;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_RETIRAR_PEPResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEPResponse ZF_PEP_RETIRAR_PEPResponse;
        
        public ZF_PEP_RETIRAR_PEPResponse1() {
        }
        
        public ZF_PEP_RETIRAR_PEPResponse1(MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEPResponse ZF_PEP_RETIRAR_PEPResponse) {
            this.ZF_PEP_RETIRAR_PEPResponse = ZF_PEP_RETIRAR_PEPResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_PEP_RETIRAR_PEPChannel : MRZCV.Retirar_pep.ZWS_PEP_RETIRAR_PEP, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_PEP_RETIRAR_PEPClient : System.ServiceModel.ClientBase<MRZCV.Retirar_pep.ZWS_PEP_RETIRAR_PEP>, MRZCV.Retirar_pep.ZWS_PEP_RETIRAR_PEP {
        
        public ZWS_PEP_RETIRAR_PEPClient() {
        }
        
        public ZWS_PEP_RETIRAR_PEPClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_PEP_RETIRAR_PEPClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_RETIRAR_PEPClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_RETIRAR_PEPClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEPResponse1 MRZCV.Retirar_pep.ZWS_PEP_RETIRAR_PEP.ZF_PEP_RETIRAR_PEP(MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEPRequest request) {
            return base.Channel.ZF_PEP_RETIRAR_PEP(request);
        }
        
        public MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEPResponse ZF_PEP_RETIRAR_PEP(MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEP ZF_PEP_RETIRAR_PEP1) {
            MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEPRequest inValue = new MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEPRequest();
            inValue.ZF_PEP_RETIRAR_PEP = ZF_PEP_RETIRAR_PEP1;
            MRZCV.Retirar_pep.ZF_PEP_RETIRAR_PEPResponse1 retVal = ((MRZCV.Retirar_pep.ZWS_PEP_RETIRAR_PEP)(this)).ZF_PEP_RETIRAR_PEP(inValue);
            return retVal.ZF_PEP_RETIRAR_PEPResponse;
        }
    }
}
