//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRZCV.Status_qualidade {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="Status_qualidade.ZWS_PEP_ENVIO_STATUS_CONT_QUAL")]
    public interface ZWS_PEP_ENVIO_STATUS_CONT_QUAL {
        
        // CODEGEN: Generating message contract since the operation ZF_PEP_ENVIO_STATUS_CONT_QUAL is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUALResponse1 ZF_PEP_ENVIO_STATUS_CONT_QUAL(MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUALRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_ENVIO_STATUS_CONT_QUAL : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESCRICAO_INField;
        
        private string hOSTField;
        
        private string mRZ1Field;
        
        private string mRZ2Field;
        
        private string sTATUS_INField;
        
        private string tIPOField;
        
        private string uSERField;
        
        private string vERIFICACAOCHIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DESCRICAO_IN {
            get {
                return this.dESCRICAO_INField;
            }
            set {
                this.dESCRICAO_INField = value;
                this.RaisePropertyChanged("DESCRICAO_IN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string HOST {
            get {
                return this.hOSTField;
            }
            set {
                this.hOSTField = value;
                this.RaisePropertyChanged("HOST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string MRZ1 {
            get {
                return this.mRZ1Field;
            }
            set {
                this.mRZ1Field = value;
                this.RaisePropertyChanged("MRZ1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MRZ2 {
            get {
                return this.mRZ2Field;
            }
            set {
                this.mRZ2Field = value;
                this.RaisePropertyChanged("MRZ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string STATUS_IN {
            get {
                return this.sTATUS_INField;
            }
            set {
                this.sTATUS_INField = value;
                this.RaisePropertyChanged("STATUS_IN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
                this.RaisePropertyChanged("TIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
                this.RaisePropertyChanged("USER");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string VERIFICACAOCHIP {
            get {
                return this.vERIFICACAOCHIPField;
            }
            set {
                this.vERIFICACAOCHIPField = value;
                this.RaisePropertyChanged("VERIFICACAOCHIP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZENUMPEP : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nUM_PEPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string NUM_PEP {
            get {
                return this.nUM_PEPField;
            }
            set {
                this.nUM_PEPField = value;
                this.RaisePropertyChanged("NUM_PEP");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_ENVIO_STATUS_CONT_QUALResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESCRICAO_OUTField;
        
        private string dESTINOField;
        
        private ZENUMPEP[] lISTAField;
        
        private string lOTEField;
        
        private string qUANTIDADEField;
        
        private string sTATUS_OUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DESCRICAO_OUT {
            get {
                return this.dESCRICAO_OUTField;
            }
            set {
                this.dESCRICAO_OUTField = value;
                this.RaisePropertyChanged("DESCRICAO_OUT");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DESTINO {
            get {
                return this.dESTINOField;
            }
            set {
                this.dESTINOField = value;
                this.RaisePropertyChanged("DESTINO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ZENUMPEP[] LISTA {
            get {
                return this.lISTAField;
            }
            set {
                this.lISTAField = value;
                this.RaisePropertyChanged("LISTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOTE {
            get {
                return this.lOTEField;
            }
            set {
                this.lOTEField = value;
                this.RaisePropertyChanged("LOTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string QUANTIDADE {
            get {
                return this.qUANTIDADEField;
            }
            set {
                this.qUANTIDADEField = value;
                this.RaisePropertyChanged("QUANTIDADE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string STATUS_OUT {
            get {
                return this.sTATUS_OUTField;
            }
            set {
                this.sTATUS_OUTField = value;
                this.RaisePropertyChanged("STATUS_OUT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_ENVIO_STATUS_CONT_QUALRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUAL ZF_PEP_ENVIO_STATUS_CONT_QUAL;
        
        public ZF_PEP_ENVIO_STATUS_CONT_QUALRequest() {
        }
        
        public ZF_PEP_ENVIO_STATUS_CONT_QUALRequest(MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUAL ZF_PEP_ENVIO_STATUS_CONT_QUAL) {
            this.ZF_PEP_ENVIO_STATUS_CONT_QUAL = ZF_PEP_ENVIO_STATUS_CONT_QUAL;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_ENVIO_STATUS_CONT_QUALResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUALResponse ZF_PEP_ENVIO_STATUS_CONT_QUALResponse;
        
        public ZF_PEP_ENVIO_STATUS_CONT_QUALResponse1() {
        }
        
        public ZF_PEP_ENVIO_STATUS_CONT_QUALResponse1(MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUALResponse ZF_PEP_ENVIO_STATUS_CONT_QUALResponse) {
            this.ZF_PEP_ENVIO_STATUS_CONT_QUALResponse = ZF_PEP_ENVIO_STATUS_CONT_QUALResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_PEP_ENVIO_STATUS_CONT_QUALChannel : MRZCV.Status_qualidade.ZWS_PEP_ENVIO_STATUS_CONT_QUAL, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_PEP_ENVIO_STATUS_CONT_QUALClient : System.ServiceModel.ClientBase<MRZCV.Status_qualidade.ZWS_PEP_ENVIO_STATUS_CONT_QUAL>, MRZCV.Status_qualidade.ZWS_PEP_ENVIO_STATUS_CONT_QUAL {
        
        public ZWS_PEP_ENVIO_STATUS_CONT_QUALClient() {
        }
        
        public ZWS_PEP_ENVIO_STATUS_CONT_QUALClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_PEP_ENVIO_STATUS_CONT_QUALClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_ENVIO_STATUS_CONT_QUALClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_ENVIO_STATUS_CONT_QUALClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUALResponse1 MRZCV.Status_qualidade.ZWS_PEP_ENVIO_STATUS_CONT_QUAL.ZF_PEP_ENVIO_STATUS_CONT_QUAL(MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUALRequest request) {
            return base.Channel.ZF_PEP_ENVIO_STATUS_CONT_QUAL(request);
        }
        
        public MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUALResponse ZF_PEP_ENVIO_STATUS_CONT_QUAL(MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUAL ZF_PEP_ENVIO_STATUS_CONT_QUAL1) {
            MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUALRequest inValue = new MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUALRequest();
            inValue.ZF_PEP_ENVIO_STATUS_CONT_QUAL = ZF_PEP_ENVIO_STATUS_CONT_QUAL1;
            MRZCV.Status_qualidade.ZF_PEP_ENVIO_STATUS_CONT_QUALResponse1 retVal = ((MRZCV.Status_qualidade.ZWS_PEP_ENVIO_STATUS_CONT_QUAL)(this)).ZF_PEP_ENVIO_STATUS_CONT_QUAL(inValue);
            return retVal.ZF_PEP_ENVIO_STATUS_CONT_QUALResponse;
        }
    }
}
