//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRZCV.Fechar_sessao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="Fechar_sessao.ZWS_PEP_FECHAR_SESSAO")]
    public interface ZWS_PEP_FECHAR_SESSAO {
        
        // CODEGEN: Generating message contract since the operation ZF_PEP_FECHAR_SESSAO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAOResponse1 ZF_PEP_FECHAR_SESSAO(MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_FECHAR_SESSAO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hOSTField;
        
        private string tIPOField;
        
        private string tRANSPORTADORAField;
        
        private string uSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string HOST {
            get {
                return this.hOSTField;
            }
            set {
                this.hOSTField = value;
                this.RaisePropertyChanged("HOST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
                this.RaisePropertyChanged("TIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TRANSPORTADORA {
            get {
                return this.tRANSPORTADORAField;
            }
            set {
                this.tRANSPORTADORAField = value;
                this.RaisePropertyChanged("TRANSPORTADORA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
                this.RaisePropertyChanged("USER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_FECHAR_SESSAOResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESCRICAOField;
        
        private string sTATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DESCRICAO {
            get {
                return this.dESCRICAOField;
            }
            set {
                this.dESCRICAOField = value;
                this.RaisePropertyChanged("DESCRICAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_FECHAR_SESSAORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAO ZF_PEP_FECHAR_SESSAO;
        
        public ZF_PEP_FECHAR_SESSAORequest() {
        }
        
        public ZF_PEP_FECHAR_SESSAORequest(MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAO ZF_PEP_FECHAR_SESSAO) {
            this.ZF_PEP_FECHAR_SESSAO = ZF_PEP_FECHAR_SESSAO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_FECHAR_SESSAOResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAOResponse ZF_PEP_FECHAR_SESSAOResponse;
        
        public ZF_PEP_FECHAR_SESSAOResponse1() {
        }
        
        public ZF_PEP_FECHAR_SESSAOResponse1(MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAOResponse ZF_PEP_FECHAR_SESSAOResponse) {
            this.ZF_PEP_FECHAR_SESSAOResponse = ZF_PEP_FECHAR_SESSAOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_PEP_FECHAR_SESSAOChannel : MRZCV.Fechar_sessao.ZWS_PEP_FECHAR_SESSAO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_PEP_FECHAR_SESSAOClient : System.ServiceModel.ClientBase<MRZCV.Fechar_sessao.ZWS_PEP_FECHAR_SESSAO>, MRZCV.Fechar_sessao.ZWS_PEP_FECHAR_SESSAO {
        
        public ZWS_PEP_FECHAR_SESSAOClient() {
        }
        
        public ZWS_PEP_FECHAR_SESSAOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_PEP_FECHAR_SESSAOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_FECHAR_SESSAOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_FECHAR_SESSAOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAOResponse1 MRZCV.Fechar_sessao.ZWS_PEP_FECHAR_SESSAO.ZF_PEP_FECHAR_SESSAO(MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAORequest request) {
            return base.Channel.ZF_PEP_FECHAR_SESSAO(request);
        }
        
        public MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAOResponse ZF_PEP_FECHAR_SESSAO(MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAO ZF_PEP_FECHAR_SESSAO1) {
            MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAORequest inValue = new MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAORequest();
            inValue.ZF_PEP_FECHAR_SESSAO = ZF_PEP_FECHAR_SESSAO1;
            MRZCV.Fechar_sessao.ZF_PEP_FECHAR_SESSAOResponse1 retVal = ((MRZCV.Fechar_sessao.ZWS_PEP_FECHAR_SESSAO)(this)).ZF_PEP_FECHAR_SESSAO(inValue);
            return retVal.ZF_PEP_FECHAR_SESSAOResponse;
        }
    }
}
