//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRZCV.Re_imprimir {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="Re_imprimir.ZWS_PEP_REIMPRESSAO")]
    public interface ZWS_PEP_REIMPRESSAO {
        
        // CODEGEN: Generating message contract since the operation ZF_PEP_REIMPRESSAO is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAOResponse1 ZF_PEP_REIMPRESSAO(MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAORequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_REIMPRESSAO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string gUIA_EXPEDICAOField;
        
        private string hOSTField;
        
        private string lOTE_INField;
        
        private string mRZ1Field;
        
        private string mRZ2Field;
        
        private string tIPO_INField;
        
        private string tRANSPORTADORAField;
        
        private string uSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string GUIA_EXPEDICAO {
            get {
                return this.gUIA_EXPEDICAOField;
            }
            set {
                this.gUIA_EXPEDICAOField = value;
                this.RaisePropertyChanged("GUIA_EXPEDICAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string HOST {
            get {
                return this.hOSTField;
            }
            set {
                this.hOSTField = value;
                this.RaisePropertyChanged("HOST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string LOTE_IN {
            get {
                return this.lOTE_INField;
            }
            set {
                this.lOTE_INField = value;
                this.RaisePropertyChanged("LOTE_IN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string MRZ1 {
            get {
                return this.mRZ1Field;
            }
            set {
                this.mRZ1Field = value;
                this.RaisePropertyChanged("MRZ1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string MRZ2 {
            get {
                return this.mRZ2Field;
            }
            set {
                this.mRZ2Field = value;
                this.RaisePropertyChanged("MRZ2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TIPO_IN {
            get {
                return this.tIPO_INField;
            }
            set {
                this.tIPO_INField = value;
                this.RaisePropertyChanged("TIPO_IN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TRANSPORTADORA {
            get {
                return this.tRANSPORTADORAField;
            }
            set {
                this.tRANSPORTADORAField = value;
                this.RaisePropertyChanged("TRANSPORTADORA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
                this.RaisePropertyChanged("USER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_REIMPRESSAOResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESCRICAOField;
        
        private string sTATUSField;
        
        private string tIPO_OUTField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DESCRICAO {
            get {
                return this.dESCRICAOField;
            }
            set {
                this.dESCRICAOField = value;
                this.RaisePropertyChanged("DESCRICAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TIPO_OUT {
            get {
                return this.tIPO_OUTField;
            }
            set {
                this.tIPO_OUTField = value;
                this.RaisePropertyChanged("TIPO_OUT");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_REIMPRESSAORequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAO ZF_PEP_REIMPRESSAO;
        
        public ZF_PEP_REIMPRESSAORequest() {
        }
        
        public ZF_PEP_REIMPRESSAORequest(MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAO ZF_PEP_REIMPRESSAO) {
            this.ZF_PEP_REIMPRESSAO = ZF_PEP_REIMPRESSAO;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_REIMPRESSAOResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAOResponse ZF_PEP_REIMPRESSAOResponse;
        
        public ZF_PEP_REIMPRESSAOResponse1() {
        }
        
        public ZF_PEP_REIMPRESSAOResponse1(MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAOResponse ZF_PEP_REIMPRESSAOResponse) {
            this.ZF_PEP_REIMPRESSAOResponse = ZF_PEP_REIMPRESSAOResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_PEP_REIMPRESSAOChannel : MRZCV.Re_imprimir.ZWS_PEP_REIMPRESSAO, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_PEP_REIMPRESSAOClient : System.ServiceModel.ClientBase<MRZCV.Re_imprimir.ZWS_PEP_REIMPRESSAO>, MRZCV.Re_imprimir.ZWS_PEP_REIMPRESSAO {
        
        public ZWS_PEP_REIMPRESSAOClient() {
        }
        
        public ZWS_PEP_REIMPRESSAOClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_PEP_REIMPRESSAOClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_REIMPRESSAOClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_REIMPRESSAOClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAOResponse1 MRZCV.Re_imprimir.ZWS_PEP_REIMPRESSAO.ZF_PEP_REIMPRESSAO(MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAORequest request) {
            return base.Channel.ZF_PEP_REIMPRESSAO(request);
        }
        
        public MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAOResponse ZF_PEP_REIMPRESSAO(MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAO ZF_PEP_REIMPRESSAO1) {
            MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAORequest inValue = new MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAORequest();
            inValue.ZF_PEP_REIMPRESSAO = ZF_PEP_REIMPRESSAO1;
            MRZCV.Re_imprimir.ZF_PEP_REIMPRESSAOResponse1 retVal = ((MRZCV.Re_imprimir.ZWS_PEP_REIMPRESSAO)(this)).ZF_PEP_REIMPRESSAO(inValue);
            return retVal.ZF_PEP_REIMPRESSAOResponse;
        }
    }
}
