//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRZCV.Fechar_caixa {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="Fechar_caixa.ZWS_PEP_FECHAR_CAIXA")]
    public interface ZWS_PEP_FECHAR_CAIXA {
        
        // CODEGEN: Generating message contract since the operation ZF_PEP_FECHAR_CAIXA is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXAResponse1 ZF_PEP_FECHAR_CAIXA(MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXARequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_FECHAR_CAIXA : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hOSTField;
        
        private string lOTE_INField;
        
        private string tIPOField;
        
        private string uSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string HOST {
            get {
                return this.hOSTField;
            }
            set {
                this.hOSTField = value;
                this.RaisePropertyChanged("HOST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string LOTE_IN {
            get {
                return this.lOTE_INField;
            }
            set {
                this.lOTE_INField = value;
                this.RaisePropertyChanged("LOTE_IN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
                this.RaisePropertyChanged("TIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
                this.RaisePropertyChanged("USER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_FECHAR_CAIXAResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESCRICAOField;
        
        private string sTATUSField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DESCRICAO {
            get {
                return this.dESCRICAOField;
            }
            set {
                this.dESCRICAOField = value;
                this.RaisePropertyChanged("DESCRICAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_FECHAR_CAIXARequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXA ZF_PEP_FECHAR_CAIXA;
        
        public ZF_PEP_FECHAR_CAIXARequest() {
        }
        
        public ZF_PEP_FECHAR_CAIXARequest(MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXA ZF_PEP_FECHAR_CAIXA) {
            this.ZF_PEP_FECHAR_CAIXA = ZF_PEP_FECHAR_CAIXA;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_FECHAR_CAIXAResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXAResponse ZF_PEP_FECHAR_CAIXAResponse;
        
        public ZF_PEP_FECHAR_CAIXAResponse1() {
        }
        
        public ZF_PEP_FECHAR_CAIXAResponse1(MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXAResponse ZF_PEP_FECHAR_CAIXAResponse) {
            this.ZF_PEP_FECHAR_CAIXAResponse = ZF_PEP_FECHAR_CAIXAResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_PEP_FECHAR_CAIXAChannel : MRZCV.Fechar_caixa.ZWS_PEP_FECHAR_CAIXA, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_PEP_FECHAR_CAIXAClient : System.ServiceModel.ClientBase<MRZCV.Fechar_caixa.ZWS_PEP_FECHAR_CAIXA>, MRZCV.Fechar_caixa.ZWS_PEP_FECHAR_CAIXA {
        
        public ZWS_PEP_FECHAR_CAIXAClient() {
        }
        
        public ZWS_PEP_FECHAR_CAIXAClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_PEP_FECHAR_CAIXAClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_FECHAR_CAIXAClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_FECHAR_CAIXAClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXAResponse1 MRZCV.Fechar_caixa.ZWS_PEP_FECHAR_CAIXA.ZF_PEP_FECHAR_CAIXA(MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXARequest request) {
            return base.Channel.ZF_PEP_FECHAR_CAIXA(request);
        }
        
        public MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXAResponse ZF_PEP_FECHAR_CAIXA(MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXA ZF_PEP_FECHAR_CAIXA1) {
            MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXARequest inValue = new MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXARequest();
            inValue.ZF_PEP_FECHAR_CAIXA = ZF_PEP_FECHAR_CAIXA1;
            MRZCV.Fechar_caixa.ZF_PEP_FECHAR_CAIXAResponse1 retVal = ((MRZCV.Fechar_caixa.ZWS_PEP_FECHAR_CAIXA)(this)).ZF_PEP_FECHAR_CAIXA(inValue);
            return retVal.ZF_PEP_FECHAR_CAIXAResponse;
        }
    }
}
