//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRZCV.validar_user {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", ConfigurationName="validar_user.ZWS_PEP_VALIDA_UTILIZADOR")]
    public interface ZWS_PEP_VALIDA_UTILIZADOR {
        
        // CODEGEN: Generating message contract since the operation ZF_PEP_VALIDA_UTILIZADOR is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADORResponse1 ZF_PEP_VALIDA_UTILIZADOR(MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADORRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_VALIDA_UTILIZADOR : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string uSERField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string USER {
            get {
                return this.uSERField;
            }
            set {
                this.uSERField = value;
                this.RaisePropertyChanged("USER");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn:sap-com:document:sap:rfc:functions")]
    public partial class ZF_PEP_VALIDA_UTILIZADORResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string dESCRICAOField;
        
        private string dESTINOField;
        
        private string[] lISTAField;
        
        private string lOTEField;
        
        private string sTATUSField;
        
        private string tIPOField;
        
        private string tOTALField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DESCRICAO {
            get {
                return this.dESCRICAOField;
            }
            set {
                this.dESCRICAOField = value;
                this.RaisePropertyChanged("DESCRICAO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string DESTINO {
            get {
                return this.dESTINOField;
            }
            set {
                this.dESTINOField = value;
                this.RaisePropertyChanged("DESTINO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] LISTA {
            get {
                return this.lISTAField;
            }
            set {
                this.lISTAField = value;
                this.RaisePropertyChanged("LISTA");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string LOTE {
            get {
                return this.lOTEField;
            }
            set {
                this.lOTEField = value;
                this.RaisePropertyChanged("LOTE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string STATUS {
            get {
                return this.sTATUSField;
            }
            set {
                this.sTATUSField = value;
                this.RaisePropertyChanged("STATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string TIPO {
            get {
                return this.tIPOField;
            }
            set {
                this.tIPOField = value;
                this.RaisePropertyChanged("TIPO");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string TOTAL {
            get {
                return this.tOTALField;
            }
            set {
                this.tOTALField = value;
                this.RaisePropertyChanged("TOTAL");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_VALIDA_UTILIZADORRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADOR ZF_PEP_VALIDA_UTILIZADOR;
        
        public ZF_PEP_VALIDA_UTILIZADORRequest() {
        }
        
        public ZF_PEP_VALIDA_UTILIZADORRequest(MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADOR ZF_PEP_VALIDA_UTILIZADOR) {
            this.ZF_PEP_VALIDA_UTILIZADOR = ZF_PEP_VALIDA_UTILIZADOR;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ZF_PEP_VALIDA_UTILIZADORResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:sap-com:document:sap:rfc:functions", Order=0)]
        public MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADORResponse ZF_PEP_VALIDA_UTILIZADORResponse;
        
        public ZF_PEP_VALIDA_UTILIZADORResponse1() {
        }
        
        public ZF_PEP_VALIDA_UTILIZADORResponse1(MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADORResponse ZF_PEP_VALIDA_UTILIZADORResponse) {
            this.ZF_PEP_VALIDA_UTILIZADORResponse = ZF_PEP_VALIDA_UTILIZADORResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ZWS_PEP_VALIDA_UTILIZADORChannel : MRZCV.validar_user.ZWS_PEP_VALIDA_UTILIZADOR, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ZWS_PEP_VALIDA_UTILIZADORClient : System.ServiceModel.ClientBase<MRZCV.validar_user.ZWS_PEP_VALIDA_UTILIZADOR>, MRZCV.validar_user.ZWS_PEP_VALIDA_UTILIZADOR {
        
        public ZWS_PEP_VALIDA_UTILIZADORClient() {
        }
        
        public ZWS_PEP_VALIDA_UTILIZADORClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ZWS_PEP_VALIDA_UTILIZADORClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_VALIDA_UTILIZADORClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ZWS_PEP_VALIDA_UTILIZADORClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADORResponse1 MRZCV.validar_user.ZWS_PEP_VALIDA_UTILIZADOR.ZF_PEP_VALIDA_UTILIZADOR(MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADORRequest request) {
            return base.Channel.ZF_PEP_VALIDA_UTILIZADOR(request);
        }
        
        public MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADORResponse ZF_PEP_VALIDA_UTILIZADOR(MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADOR ZF_PEP_VALIDA_UTILIZADOR1) {
            MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADORRequest inValue = new MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADORRequest();
            inValue.ZF_PEP_VALIDA_UTILIZADOR = ZF_PEP_VALIDA_UTILIZADOR1;
            MRZCV.validar_user.ZF_PEP_VALIDA_UTILIZADORResponse1 retVal = ((MRZCV.validar_user.ZWS_PEP_VALIDA_UTILIZADOR)(this)).ZF_PEP_VALIDA_UTILIZADOR(inValue);
            return retVal.ZF_PEP_VALIDA_UTILIZADORResponse;
        }
    }
}
