//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRZCV.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Xidev")]
        public string user {
            get {
                return ((string)(this["user"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("o6bqP5QB6v3iREO7bUFeLo9NFM07jpw1tGZy442i7vk=")]
        public string pw {
            get {
                return ((string)(this["pw"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://incmdev1.incm.int:8080/sap/bc/srt/rfc/sap/zws_pep_envio_status_cont_qual/0" +
            "20/zws_pep_envio_status_cont_qual/zws_pep_envio_status_cont_qual")]
        public string caminho_qualidade {
            get {
                return ((string)(this["caminho_qualidade"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://incmdev1.incm.int:8080/sap/bc/srt/rfc/sap/zws_pep_fechar_caixa/020/zws_pep" +
            "_fechar_caixa/zws_pep_fechar_caixa")]
        public string caminho_fecho_caixa {
            get {
                return ((string)(this["caminho_fecho_caixa"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://incmdev1.incm.int:8080/sap/bc/srt/rfc/sap/zws_pep_valida_utilizador/020/zw" +
            "s_pep_valida_utilizador/zws_pep_valida_utilizador")]
        public string caminho_validauser {
            get {
                return ((string)(this["caminho_validauser"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://incmdev1.incm.int:8080/sap/bc/srt/rfc/sap/zws_pep_envio_dados_personaliz/0" +
            "20/zws_pep_envio_dados_personaliz/zws_pep_envio_dados_personaliz")]
        public string caminho_dados_perso {
            get {
                return ((string)(this["caminho_dados_perso"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://incmdev1.incm.int:8080/sap/bc/srt/rfc/sap/zws_pep_fechar_sessao/020/zws_pe" +
            "p_fechar_sessao/zws_pep_fechar_sessao")]
        public string caminho_fecho_sesao {
            get {
                return ((string)(this["caminho_fecho_sesao"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://incmdev1.incm.int:8080/sap/bc/srt/rfc/sap/zws_pep_reimpressao/020/zws_pep_" +
            "reimpressao/zws_pep_reimpressao")]
        public string caminho_reimprimir {
            get {
                return ((string)(this["caminho_reimprimir"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://incmdev1.incm.int:8080/sap/bc/srt/rfc/sap/zws_pep_retirar_pep/020/zws_pep_" +
            "retirar_pep/zws_pep_retirar_pep")]
        public string caminho_retirar_pep {
            get {
                return ((string)(this["caminho_retirar_pep"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\server-print-pr\\A4COR")]
        public string nome_impressora {
            get {
                return ((string)(this["nome_impressora"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\Logs_Teste")]
        public string caminho_log {
            get {
                return ((string)(this["caminho_log"]));
            }
            set {
                this["caminho_log"] = value;
            }
        }
    }
}
